### ISSUE TITLE
Programmer needed!

### ISSUE THREAD

**Issue by Marc92020** [ScratchNitro/Scratch-Nitro#1]
(the original was by @JackyBorderCollie in the old scratch nitro repository. i just remade it here)
Hi! So, we need a great coder, like Jeffalo or Griffpatch, that can make browser extensions! I think we should invite Jeffalo too :)

**Comment by JackyBorderCollie** [comment]
But how do we get Jeffalo or Griffpatch to contribute?

**Comment by JackyBorderCollie** [comment]
> > But how do we get Jeffalo or Griffpatch to contribute?
> 
> We might not be able to get griffpatch but getting Jeffalo might be possible. Do you know how Scratch Addons got noticed and lots of people came to help?

Hmm, I'll look at it

**Comment by JackyBorderCollie** [comment]
Well, maybe we should tell Jeffalo

**Comment by JackyBorderCollie** [comment]
We invited Jeffalo, so I'll close this.
