### ISSUE TITLE
Rename to "Scratch Addons Deluxe"

### ISSUE THREAD

**Issue by Chaos-emerald** [ScratchNitro/Scratch-Nitro#12]
So you can say Scratch Nitro

**Comment by Marc92020** [comment]
> We are not remaking Scratch Addons. We are making a new thing called Scratch Nitro

So we are not renaming it.

**Comment by JackyBorderCollie** [comment]
As Marc92020 said, we don't plan recreating Scratch Addons, so we are not renaming it.
