### ISSUE TITLE
Adding a code to the commenting buttons

### ISSUE THREAD

**Issue by JackyBorderCollie** [ScratchNitro/Scratch-Nitro#7]
So, I have learned some JavaScript, and I tried it on the commenting GUI, but I cannot get the buttons to work, for some reason. So, I need help.

**Comment by Marc92020** [comment]
Hmmm... I'm not good at javascript. I only know some html. This will be hard. and Jeffalo still has not joined

**Comment by JackyBorderCollie** [comment]
Yup, It'll be hard, but I'll try until I success. Also, I can search on Google for tutorials :)
