### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by zahmbie1** [ScratchNitro/Scratch-Nitro#9]
The question is... why.

**Comment by JackyBorderCollie** [comment]
We want others to experience Scratch Nitro features too

**Comment by zahmbie1** [comment]
Why not contribute to ScratchAddons like somebody would do?

**Comment by Marc92020** [comment]
> contribute to ScratchAddons like somebody would do

Well I contribute to Scratch Addons but this is a cool idea.

**Comment by JackyBorderCollie** [comment]
> > contribute to ScratchAddons like somebody would do
> 
> Well I contribute to Scratch Addons but this is a cool idea.

How to contribute to Scratch Addons?
